logging:
    level:
        com.language.word: DEBUG

server:
    port: 8070

spring:
    application:
        name: language-config
    profiles:
        active: native

#http://localhost:8070/word/gray