spring:
    datasource:
        driverClass: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.181.129:3306/study_system?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        user: root
        password: 1234qwer
        acquireIncrement: 1
        initialPoolSize: 2
        maxIdleTime: 2
        maxPoolSize: 2
        minPoolSize: 2
        acquireRetryDelay: 1000
        acquireRetryAttempts: 60
        minPoolSizebreakAfterAcquireFailure: false


gt:
  source:
      appId: YV2YjDZ7me8UcddAs4N8v9
      appKey: YHfxULdlFw66H8hfRnJSW6
      masterSecret: G04OLabOjl6thG5HVD3sF2
      url: http://sdk.open.api.igexin.com/apiex.htm

