logging:
    level:
        com.language.word: DEBUG

local:
    server:
        port: 8080

spring:
    application:
        name: language-word
    boot:
        admin:
#            url: http://localhost:8172/komovie-monitor
    datasource:
        name: dev
        url: jdbc:mysql://192.168.181.129:3306/study_system
        username: root
        password: 1234qwer
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver